services:
  task_donegeon:
    build:
      context: .
      dockerfile: Dockerfile.prod
    pull_policy: always
    ports:
      - "5485:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1  # Ensure Python output is sent to container logs
      - PYTHONTRACEMALLOC=1 # Enable memory tracing
      - PYTHONFAULTHANDLER=1 # Enable fault handler for better crash reports
      - SECRET_KEY=${SECRET_KEY:-changeme_in_production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - BASE_PATH=${BASE_PATH:-/data}
    volumes:
      - ${BASE_PATH}/config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"  # Increased from 10m
        max-file: "5"    # Increased from 3
        mode: "non-blocking"
        max-buffer-size: "4m"
        tag: "{{.Name}}"
        labels: "production,task_donegeon"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  task_donegeon_data:
    name: task_donegeon_data
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH:-/var/lib/task_donegeon/data}
      o: bind
  task_donegeon_config:
    name: task_donegeon_config
    driver: local
    driver_opts:
      type: none
      device: ${CONFIG_PATH:-/var/lib/task_donegeon/config}
      o: bind
  task_donegeon_uploads:
    name: task_donegeon_uploads
    driver: local
    driver_opts:
      type: none
      device: ${UPLOADS_PATH:-/var/lib/task_donegeon/uploads}
      o: bind 