services:
  task_donegeon:
    build: .
    ports:
      - "5485:5000"
    environment:
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY:-default_dev_key_please_change}
    volumes:
      - task_donegeon_config:/app/config   # For configuration files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped  # Add automatic restart policy

volumes:
  task_donegeon_config:
    name: task_donegeon_config 