version: '3.8'
services:
  task_donegeon:
    build: .
    ports:
      - "5485:5000"
    environment:
      - PORT=5000
    volumes:
      - task_donegeon_data:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  task_donegeon_data: 