services:
  task_donegeon:
    volumes:
      - ./:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --reload
    ports:
      - "5000:5000" 